CREATE DATABASE DUMOCK;

##系统信息表
DROP TABLE IF EXISTS DUMOCK_D_SYSTEM;
create table DUMOCK_D_SYSTEM(
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键，id',
  NAME VARCHAR(20) NOT NULL COMMENT '名称',
  DESCRIPTION VARCHAR(400) COMMENT '描述',
  CREATE_TIME DATETIME NOT NULL COMMENT '修改时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间'
)DEFAULT CHARSET=utf8;

##接口相关表
###facade信息表
DROP TABLE IF EXISTS DUMOCK_D_FACADE;
create table DUMOCK_D_FACADE(
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键，id',
  SYSTEM_UNIQUE_KEY VARCHAR(256) not null COMMENT '系统唯一键',
  NAME VARCHAR(100) NOT NULl COMMENT '名称',
  DESCRIPTION VARCHAR(400) COMMENT '描述',
  VERSION VARCHAR(100) NOT NULL COMMENT '版本号',
  CREATE_TIME DATETIME NOT NULL COMMENT '修改时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间'
)DEFAULT CHARSET=utf8;

###method信息表
DROP TABLE IF EXISTS DUMOCK_D_METHOD;
CREATE TABLE DUMOCK_D_METHOD (
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键，id',
  FACADE_ID bigint(20) not null COMMENT 'facadeId，对应所属facade',
  DESCRIPTION VARCHAR(400) COMMENT '描述',
  PARAM_TYPE TEXT COMMENT '请求参数类型',
  RETURN_TYPE TEXT COMMENT '返回类型',
  PARAM_JSON_DATA TEXT COMMENT '请求参数类型',
  RETURN_JSON_DATA TEXT COMMENT '返回参数数据',
  CREATE_TIME DATETIME NOT NULL COMMENT '修改时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间'
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DUMOCK_D_METHOD_CONTROLLER;
##方法控制表
CREATE TABLE DUMOCK_D_METHOD_CONTROLLER(
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键，id',
  METHOD_ID bigint(20) not null COMMENT '方法ID',
  USER_NAME VARCHAR(100) not null COMMENT '用户名',
  IS_MOCK VARCHAR(10) NOT NULL COMMENT '是否MOCK',
  IS_TIME_OUT VARCHAR(10) NOT NULL COMMENT '是否超时',
  TIME_OUT_LENGTH INTEGER NOT NULL COMMENT '超时时间' DEFAULT 3000,
  CREATE_TIME DATETIME NOT NULL COMMENT '修改时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间'
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DUMOCK_D_USER_INFO;
CREATE TABLE DUMOCK_D_USER_INFO(
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键，id',
  LOGIN_NAME VARCHAR(100) not null COMMENT '登录名',
  USER_NAME VARCHAR(100) not NULL COMMENT '用户名',
  USER_PWD VARCHAR(128) COMMENT '用户密码',
  CREATE_TIME DATETIME NOT NULL COMMENT '修改时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间'
)DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DUMOCK_D_JAR_FILE_MANAGER;
CREATE TABLE DUMOCK_D_JAR_FILE_MANAGER(
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键，id',
  GROUP_ID VARCHAR(256) not null COMMENT 'groupId',
  ARTIFACT_ID VARCHAR(100) not null COMMENT 'artifactId',
  SYSTEM_UNIQUE_KEY VARCHAR(256) not null COMMENT '系统唯一键',
  VERSION VARCHAR(100) not NULL  COMMENT 'version',
  JAR_FILE_NAME VARCHAR(100) NOT NULL COMMENT 'jar包名称',
  JAR_FILE_PATH VARCHAR(256) NOT NULL COMMENT 'jar包存放路径',
  CREATE_TIME DATETIME NOT NULL COMMENT '修改时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间'
)DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS DUMOCK_D_CALL_RECORD;
CREATE TABLE DUMOCK_D_CALL_RECORD(
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键,id',
  USER_NAME VARCHAR(100) not null COMMENT '用户名',
  INTERFACE_NAME VARCHAR(100) NOT NULL COMMENT '接口名称',
  METHOD_NAME VARCHAR(100) NOT NULL COMMENT '方法名称',
  IS_MOCK VARCHAR(10) NOT NULL COMMENT '是否Mock',
  IS_TIMEOUT VARCHAR(10) NOT NULL COMMENT '是否超时',
  CALL_STATUS VARCHAR(10) NOT NULL COMMENT '调用状态',
  CALL_RESULT_ID bigint(20) not null COMMENT '调用结果ID',
  CREATE_TIME DATETIME NOT NULL COMMENT '修改时间',
  UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间'
)DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS DUMOCK_D_CALL_RESULT;
CREATE TABLE DUMOCK_D_CALL_RESULT(
  ID bigint(20) not null AUTO_INCREMENT PRIMARY KEY COMMENT '主键,id',
  RESULT TEXT not NULL COMMENT '调用结果'
)